print("What is your name human?")
name = input ()
print("How old are you in years?")
age = int (input())
print("How tall are you in meters?")
height = float (input())
print("How much do you weigh?")
weight = float (input())
bmi = int(weight) / float(height**2)
print(bmi)
print ("Hi Dhafu",name, "your are only",age, "but your BMI is",bmi)
