print ("Please enter the number of lives")
number_of_lives = int (input())
lives_symbol = ("♥")
print ("Please enter energy level.")
energy_level = int (input())
energy_symbol = ("♦")
print ("Please enter shield level.")
shield_level = int (input())
shield_symbol = ("♦")
print ("Lives:",number_of_lives*lives_symbol)
print ("Energy:",energy_level*energy_symbol)
print ("Shield:",shield_level*shield_symbol)